version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  registerDefaultExceptionMappers: false

logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: info
# enable debug logging to a file here:
#    - type: file
#      currentLogFilename: ./logs/debug.log
#      archivedLogFilenamePattern: ./logs/debug-%d{yyyy-MM-dd-HH}.log.gz
#      archivedFileCount: 4
